spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/chess-platform-realm

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay

        - id: matchmaking-service
          uri: lb://matchmaking-service
          predicates:
            - Path=/api/matchmaking/**

          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay

        - id: social-friends
          uri: lb://social-community-service
          predicates:
            - Path=/api/friends/**
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay
        - id: social-chats
          uri: lb://social-community-service
          predicates:
            - Path=/api/chats/**
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/ws-notifications/**
          filters:
            - TokenRelay

        - id: game-management-service-api
          uri: lb://game-management-service
          predicates:
            - Path=/api/games/**
          filters:
            - TokenRelay

        - id: game-management-service-ws
          uri: lb://game-management-service
          predicates:
            - Path=/ws-game/**
          filters:
            - TokenRelay

      discovery:
        locator:
          enabled: true
          lower-case-service: true


  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8082
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG