
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/chess-platform-realm
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  data:
    redis:
      port: 6380
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/game-management-service
    username: postgres
    password: postgres
  application:
    name: game-management-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8088
