spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/chess-platform-realm
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: false
  application:
    name: matchmaking-service
  data:
    redis:
      port: 6379
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8085
game-management-service:
  url: http://localhost:8088
notification-service:
  url: http://localhost:8090