
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: false
  application:
    name: matchmaking-service
  data:
    redis:
      port: 6379
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8085
