spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/chess-platform-realm
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8084

keycloak:
  auth-server-url: http://localhost:8888
  realm: chess-platform-realm
  resource: user-service
  credentials:
    secret: QIL403vQ3myWdSdS4HnQ0rl6ubUPMVNx